### ISSUE TITLE
Failed reading core package header

### ISSUE THREAD

**Issue by wpkato** [stefancrain/folding-at-home#21]
I have recently been receiving this error in the logs:

15:42:13:WU00:FS00:Downloading core from http://cores.foldingathome.org/lin/64bit-avx2-256/a8-0.0.12/Core_a8.fah
15:42:13:WU00:FS00:Connecting to cores.foldingathome.org:80
15:42:13:ERROR:WU00:FS00:Exception: Failed reading core package header.
15:42:14:WU01:FS01:Downloading core from http://cores.foldingathome.org/lin/64bit/22-0.0.20/Core_22.fah
15:42:14:WU01:FS01:Connecting to cores.foldingathome.org:80
15:42:14:ERROR:WU01:FS01:Exception: Failed reading core package header.

F@H dashboard shows both CPU and GPU processing in the yellow "ready" stage.

I would appreciate any help.  Thanks in advance.

**Comment by stefancrain** [comment]
Could you share some details on how you are executing the container / what GPUs you are using?

**Comment by wpkato** [comment]
- Here's my docker-compose (personal info edited)

version: "3"
services:
  folding-at-home:
    image: stefancrain/folding-at-home:latest
    container_name: folding-at-home
    ports:
      - 7396:7396
    restart: unless-stopped
    command: ["--user=xxxxx","--team=XXXXXX","--power=full","--gpu=true","--cpu-usage=100"]

- I'm using a NVidia Quadro P2000 card.  The card is recognized and utilized by another container (Jellyfin) in Docker so I'm confident it's setup correctly

**Comment by stefancrain** [comment]
Thanks for that. Taking a look.

**Comment by wpkato** [comment]
I don't know what to say but after a few hours, both tabs (CPU and GPU) started processing.

I didn't touch it or make any adjustments so I can't tell you why this happened.  You can close this ticket if you wish.

Thanks again for your help.

**Comment by stefancrain** [comment]
> Failed reading core package header.

That's good news at least! Lets hope that this was a transient network issue. My GPU node is still coming online.
