### ISSUE TITLE
is this normal or an issue?

### ISSUE THREAD

**Issue by cmspeedau** [stefancrain/folding-at-home#5]
```08:33:08:WU00:FS00:Connecting to 18.218.241.186:80                                                                                                       
08:33:09:WARNING:WU00:FS00:Failed to get assignment from '18.218.241.186:80': No WUs available for this configuration                                    
08:33:09:ERROR:WU00:FS00:Exception: Could not get an assignment  ```

**Comment by stefancrain** [comment]
Yes this is very common currently and not a client failure. The Folding@home team is struggling to keep up with demand and make work units (WUs) available. 

- https://www.reddit.com/r/Folding/comments/fjqqwm/help_failed_to_get_assignmentno_wus_available_for/
- https://twitter.com/foldingathome/status/1239992073664765953

I have read that restarting your client can give you access to WU's as you switch assignment servers, unless the entire pool is exhausted.
