### ISSUE TITLE
`docker run` aborting with error "could not select device driver "" with capabilities: [[gpu]]"

### ISSUE THREAD

**Issue by DurvalMenezes** [stefancrain/folding-at-home#7]
("Host") OS: Ubuntu 18.04
Docker version: 19.03.6 (package 'docker.io' version '19.03.6-0ubuntu1~18.04.1' installed from the Ubuntu standard distro repositories) 

Command: `sudo docker run   --name folding-at-home   --gpus all   -p 7396:7396   stefancrain/folding-at-home:latest   --user=REDACTED   --team=REDACTED   --power=full   --gpu-usage=100   --cpu-usage=100`

Result:
```
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
ERRO[0000] error waiting for container: context canceled 
```
EDIT: "Host" GPU seems to be supported by F@H (ie, I can find it on GPUs.txt:
```
01:00.0 VGA compatible controller: NVIDIA Corporation GP104GLM [Quadro P5000 Mobile] (rev a1) (prog-if 00 [VGA controller])
        Subsystem: Hewlett-Packard Company GP104GLM [Quadro P5000 Mobile]
```
Also, NVIDIA drivers are installed and working (ie, `glxinfo` and `glxgears` work), also `clinfo` works and lists the NVIDIA adapter above.

**Comment by stefancrain** [comment]
Have you installed the [NVIDIA/nvidia-docker](https://github.com/NVIDIA/nvidia-docker) device driver? Here is a [gist](https://gist.github.com/stefancrain/0b4fe2ae29a15427a5d7040a9f7cdb5c) from my headless ubuntu 18.04 setup

What is the output of this command? 

```
docker run \
 --rm \
 --gpus all \
 --entrypoint="nvidia-smi" \
 stefancrain/folding-at-home:latest```

**Comment by DurvalMenezes** [comment]
@stefancrain, thanks for your prompt response.

And you hit it on the head: the problem was not having installed NVIDIA/nvidia-docker beforehand. I just followed the installation instructions there for Ubuntu 18.04 and then removed (`docker rm .. `) and re-executed your container (`docker run ...`) and it's working now.
